name: Build and Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
    name: Build Veracode.OSS.Declare.Configuration for ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build Veracode.OSS.Declare.Configuration/Veracode.OSS.Declare.Configuration.csproj
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Veracode.OSS.Declare.Configuration/Veracode.OSS.Declare.Configuration.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
 