name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
    name: Build and NuGet Publish for Veracode.OSS.Declare.Configuration for ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}} 
      - run: dotnet build --configuration Release Veracode.OSS.Declare.Configuration/Veracode.OSS.Declare.Configuration.csproj
      - name: Push generated package to NuGet
        run: dotnet nuget push Veracode.OSS.Declare.Configuration/bin/Release/*.nupkg --skip-duplicate --no-symbols true


 